server:
  port: 7221

spring:
  application:
    name: MutantAnalyzerDB
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:    console:      enabled: true
      path: /h2-console
           
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

  rabbitmq:
    dynamic: true
    port: 5672
    username: guest
    password: guest
    host: localhost

