server:
  port: 7220

spring:
  application:
    name: MutantAnalyzer
  datasource:
    url: jdbc:h2:tcp://localhost:9090/mem:mutantDb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  h2:
    console:
      enabled: true
      settings:        web-allow-others: true
           
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    
  rabbitmq:
    dynamic: true
    port: 5672
    username: guest
    password: guest
    host: localhost